### ISSUE TITLE
Fix https request issue

### ISSUE THREAD

**Issue by jinruiyang** [jinruiyang/zeroshotdemo#1]
demos runs in the original URL ( http://dickens.seas.upenn.edu:4007/ ) it does NOT work in the proxy https URL used in CCG website ( https://cogcomp.seas.upenn.edu/dc4007/ ).

**Comment by HeglerTissot** [comment]
When we use proxy URLs for demos, the code can't make references to absolute paths like /anything because of the new root base /dc4007. In this case, everything has to be accessed by a relative path from the start point of cherrypy server. 

I believe the problem is on file public/js/predict.js line 141: 
var url = "/predict";

Maybe you should try any relative paths like:
var url = "../predict";
OR
var url = "../../predict";
OR
var url = "../../../predict";

**Comment by jinruiyang** [comment]
#
